language: ruby
rvm:
  - 2.6
before_script:
- gem install awesome_bot
- gem install mdl
script:
- awesome_bot README.md --skip-save-results --allow-redirect --allow-ssl --allow-dupe -w jinja.pocoo.org,vimeo.com # Allow duplicate links and whitelist jinja.pocoo.org
- mdl -v --rules ~MD013,~MD033 README.md # Ignore line length (MD013) and inline HTML (MD033) Rules
notifications:
  email: false
